services:
  db:
    image: postgres:15
    container_name: "redirector_database"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "redirector"
      LANG: en_US.utf8
    ports:
      - "8085:5432"
    volumes:
      - db_data:/var/lib/postgres/redirector
    networks:
      - redirector-net

#  redirector:
#    build:
#      context: ..
#      dockerfile: AppDockerfile
#    container_name: "app"
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    networks:
#      - redirector-net
#    depends_on:
#      - db

networks:
  redirector-net:
    driver: bridge

volumes:
  db_data:

