services:
  db:
    image: postgres:15
    container_name: "redirector_database"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "redirector"
      LANG: en_US.utf8
    ports:
      - "8085:5432"
    volumes:
      - db_data:/var/lib/postgres/redirector
    networks:
      - redirector-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: "redirector_redis"
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - redirector-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


  redirector:
    build:
      context: .
      dockerfile: AppDockerfile
    container_name: "redirector_app"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - REDIS_HOST=redis
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - redirector-net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  redirector-net:
    driver: bridge

volumes:
  db_data:

