server.port=8080

spring.datasource.url=jdbc:postgresql://db:5432/redirector
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.data.redis.host=${REDIS_HOST}
